version: '3.8'

services:
  backend:
    build: ./backend
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - CHROMA_PERSIST_DIR=/app/chroma_db
      - ENVIRONMENT=development
    volumes:
      - chroma_data:/app/chroma_db
      - ./backend:/app  # Mount source code for development
    ports:
      - "8000:8000"
    command: ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8000", "--reload"]
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:8000/ping || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    ports:
      - "3001:3000"  # Use port 3001 to avoid conflicts
    depends_on:
      - backend
    environment:
      - REACT_APP_API_URL=http://localhost:8000
      - CHOKIDAR_USEPOLLING=true  # For hot reload in Docker
    volumes:
      - ./frontend:/app  # Mount source code for development
      - /app/node_modules  # Anonymous volume for node_modules

volumes:
  chroma_data: