version: '3.8'

services:
  fastapi-backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: qua-bio-backend
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - ENVIRONMENT=production
      - CHROMA_PERSIST_DIR=/app/chroma_db
      - PORT=8000
      - HOST=0.0.0.0
    volumes:
      - chroma_data:/app/chroma_db
      - chroma_data_semantic:/app/chroma_db_semantic
      - app_logs:/app/logs
    ports:
      - "8000:8000"
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:8000/api/health || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

volumes:
  chroma_data:
    driver: local
  chroma_data_semantic:
    driver: local
  app_logs:
    driver: local