version: '3.8'

services:
  backend:
    build: .
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - CHROMA_PERSIST_DIR=/app/chroma_db
      - CHROMA_SEMANTIC_PERSIST_DIR=/app/chroma_db_semantic
      - ENVIRONMENT=production
    volumes:
      - chroma_data:/app/chroma_db
      - chroma_semantic_data:/app/chroma_db_semantic
    ports:
      - "8000:8000"
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:8000/api/health || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3

volumes:
  chroma_data:
  chroma_semantic_data: