# Name of your application. Used to uniquely configure containers.
service: mito

# Name of the container image.
image: matk0/mito

# Deploy to these servers.
servers:
  web:
    - 165.232.68.195

# Enable SSL auto certification via Let's Encrypt
proxy:
  ssl: true
  hosts:
    - 'knowledgebase.studio'
    - 'www.knowledgebase.studio'

# Credentials for your image host.
registry:
  username: matk0
  password:
    - KAMAL_REGISTRY_PASSWORD

# Inject ENV variables into containers
env:
  secret:
    - RAILS_MASTER_KEY
    - DATABASE_URL
  clear:
    SOLID_QUEUE_IN_PUMA: true
    DB_HOST: DB_HOST
    # FastAPI internal URL
    FASTAPI_URL: 'http://mito-fastapi:8000'
    RAILS_LOG_LEVEL: info

# Aliases
aliases:
  console: app exec --interactive --reuse "bin/rails console"
  shell: app exec --interactive --reuse "bash"
  logs: app logs -f
  dbc: app exec --interactive --reuse "bin/rails dbconsole"

# Persistent storage volumes
volumes:
  - 'mito_storage:/rails/storage'

# Bridge fingerprinted assets
asset_path: /rails/public/assets

# Configure the image builder
builder:
  arch: amd64
  remote: ssh://docker@64.225.100.110
  args:
    RUBY_VERSION: 3.3.5
  secrets:
    - RAILS_MASTER_KEY

# SSH configuration
ssh:
  user: root
  keys:
    - ~/.ssh/id_rsa

# Accessories - FastAPI backend
accessories:
  fastapi:
    image: matk0/mito-fastapi
    host: 165.232.68.195
    # Only expose internally, not to the public
    port: '127.0.0.1:8000:8000'
    env:
      clear:
        PYTHONUNBUFFERED: 1
      secret:
        - OPENAI_API_KEY
    volumes:
      - '/opt/mito/fastapi/chroma_db:/app/chroma_db'
      - '/opt/mito/fastapi/chroma_db_semantic:/app/chroma_db_semantic'
