name: Rails Deploy

on:
  push:
    branches: [main]
    paths:
      - "apps/web-gateway/**"
      - "shared/**"
      - ".github/workflows/rails-deploy.yml"
  workflow_dispatch:

defaults:
  run:
    working-directory: apps/web-gateway

jobs:
  deploy:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: .ruby-version
          bundler-cache: true
          working-directory: apps/web-gateway

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ secrets.DOCKER_REGISTRY }}
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: apps/web-gateway
          file: apps/web-gateway/Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_REGISTRY }}/web-gateway:${{ github.sha }},${{ secrets.DOCKER_REGISTRY }}/web-gateway:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.8.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Deploy with Kamal
        env:
          RAILS_MASTER_KEY: ${{ secrets.RAILS_MASTER_KEY }}
          KAMAL_REGISTRY_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        run: |
          # Install Kamal if not available
          gem install kamal
          
          # Deploy the application
          kamal deploy

      - name: Notify deployment status
        if: always()
        run: |
          if [ ${{ job.status }} == 'success' ]; then
            echo "✅ Rails deployment successful"
          else
            echo "❌ Rails deployment failed"
            exit 1
          fi